### ISSUE TITLE
"Stabilizing features" has broken links and unclear instructions

### ISSUE THREAD

**Issue by Xiretza** [rust-lang/std-dev-guide#47]
https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html has two links labeled "libs team reviewers" that lead to https://github.com/rust-lang/highfive/blob/master/highfive/configs/rust-lang/rust.json, which doesn't exist. It also says to "either ping @rust-lang/libs-api or leave a comment asking about the status of the feature", but it's not clear what "ping" means here; it seems to be distinct from "leav[ing] a comment", and even if it does mean leaving a comment with that tag in it, that doesn't appear to work (at least it doesn't get highlighted in the rendered comment like a user would be).

**Comment by JohnTitor** [comment]
> [std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html](https://std-dev-guide.rust-lang.org/feature-lifecycle/stabilization.html) has two links labeled "libs team reviewers" that lead to [rust-lang/highfive@`master`/highfive/configs/rust-lang/rust.json](https://github.com/rust-lang/highfive/blob/master/highfive/configs/rust-lang/rust.json?rgh-link-date=2023-01-07T18%3A23%3A04Z), which doesn't exist.

Because we migrated to triagebot, it now lives on https://github.com/rust-lang/rust/blob/e5d46a5bdac3f19793297914d4ada432024fbe95/triagebot.toml#L459. It's just a left-over on the migration.

> It also says to "either ping @rust-lang/libs-api or leave a comment asking about the status of the feature", but it's not clear what "ping" means here; it seems to be distinct from "leav[ing] a comment",

"ping" here means mentioning the team via a comment. Here's a formal definition: https://dictionary.cambridge.org/dictionary/english/ping

> and even if it does mean leaving a comment with that tag in it, that doesn't appear to work (at least it doesn't get highlighted in the rendered comment like a user would be).


GitHub doesn't allow you to mention the team if you aren't a part of the organization. In such a case, you can leave a comment instead (that's why we wrote "either...").
